#!/bin/bash
#
# This hook adds a file containing the current branch and commit
# hash of pprzlink into the ChibiESC repository, so that we always
# know which pprzlink commit works with a committed ChibiESC version.
# 
# The new file will not neccessarily show in the commit overview of
# the commit message template, but it is added and committed anyway.

HEADREF=$(<../pprzlink/.git/HEAD)
REFFILE=${HEADREF:5}
BRANCHNAME=`basename ../pprzlink/.git/$REFFILE`
COMMITHASH=$(<../pprzlink/.git/$REFFILE)
FILENAME=src/subsystems/pprzlink/pprzlink_commit

rm -f $FILENAME
echo "Branch: $BRANCHNAME" >> $FILENAME
echo "Commit: $COMMITHASH" >> $FILENAME
git add $FILENAME
