/*
 * svpwm.comp
 *
 *  Created on: 29.12.2016
 *      Author: joerg
 */
/*
 * Inputs für diesen Block.
 * Mode-Pin
 * 1. u,v,w
 * 2. a,b (alpha, beta)
 * 3. Betrag, Phase
Asymmetric PWM AN4013 nur auf F7!!
 */

float u,v,w;//[-1..1]
float offset = 0;
float du, dv, dw; // [0..1]

// std
offset = (u + v + w) / 3 ;


// svm
offset = (MIN(u, v, w) + MAX(u, v, w)) / 2;


// fb svm
offset = MIN(u, v, w) - 1;


du = (u - offset + 1) / 2;
dv = (v - offset + 1) / 2;
dw = (w - offset + 1) / 2;
